"use client"
import Head from "next/head";
import useSWR from "swr";
import { fetcher } from "../libs/request";

export default function Home() {
  const { data } = useSWR('/api/hello', fetcher)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <pre>{JSON.stringify(data, null, 4)}</pre>
      </div>
    </>
  );
}
